server: "hub-cloud.browserstack.com"
common_caps:
  "browserstack.user": "davidwasielewski_Yq8GOu"
  "browserstack.key": "EirMGEHFqzSpFLn8rjt8"
  "project": "First Cucumber Android Project"
  "build": "browserstack-build-1"
  "browserstack.debug": true
browser_caps:
  -
    "device": "Google Pixel 3"
    "os_version": "9.0"
    "app": "bs://c700ce60cf13ae8ed97705a55b8e022f13c5827c"
    "name": "first_test"
