server: "hub-cloud.browserstack.com"
username: "BROWSERSTACK_USERNAME"
access_key: "BROWSERSTACK_ACCESS_KEY"

common_caps:
  "project": "First Cucumber iOS Project"
  "build": "Cucumber iOS"
  "browserstack.debug": true

browser_caps:
  -
    "device": "iPhone 11 Pro"
    "os_version": "13"
    "app": "bs://<hashed app-id>"
    "browserstack.local": true
    "name": "local_test"
